// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1gA7HDZqIpIjmvgR6S5QiQ3PPEtGKBN4',
    appId: '1:831855535235:web:9c5fc6626b7433fdc8a7b6',
    messagingSenderId: '831855535235',
    projectId: 'e-commerce-9f85c',
    authDomain: 'e-commerce-9f85c.firebaseapp.com',
    storageBucket: 'e-commerce-9f85c.firebasestorage.app',
    measurementId: 'G-YQRPXMDDP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEaVCjZgGgveLDVelwrPXbz-6vPhR8Zk',
    appId: '1:831855535235:android:74792e98a41393f2c8a7b6',
    messagingSenderId: '831855535235',
    projectId: 'e-commerce-9f85c',
    storageBucket: 'e-commerce-9f85c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKVezndg_F9QNRbE8TFee-58BOfMQJjSc',
    appId: '1:831855535235:ios:6f7d014ca9aa200cc8a7b6',
    messagingSenderId: '831855535235',
    projectId: 'e-commerce-9f85c',
    storageBucket: 'e-commerce-9f85c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKVezndg_F9QNRbE8TFee-58BOfMQJjSc',
    appId: '1:831855535235:ios:6f7d014ca9aa200cc8a7b6',
    messagingSenderId: '831855535235',
    projectId: 'e-commerce-9f85c',
    storageBucket: 'e-commerce-9f85c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1gA7HDZqIpIjmvgR6S5QiQ3PPEtGKBN4',
    appId: '1:831855535235:web:1448a46f8515b33ec8a7b6',
    messagingSenderId: '831855535235',
    projectId: 'e-commerce-9f85c',
    authDomain: 'e-commerce-9f85c.firebaseapp.com',
    storageBucket: 'e-commerce-9f85c.firebasestorage.app',
    measurementId: 'G-JE1KMFC03Q',
  );
}
